# Inquiry-Based Music Theory
# OER Music text book, by Sean Butterfield and Evan Williamson
# project was inspired by and partially adapted from Open Music Theoryhttps://github.com/openmusictheory/openmusictheory.github.io

# jekyll theme partly based on Lanyon, https://github.com/poole/lanyon
# OER Music text book, content adapted and created by smbutterfield
# jekyll theme adapted from Lanyon, https://github.com/poole/lanyon
# project set up by evanwill

# site info
title: Inquiry-Based Music Theory
tagline: OER Text Book
description: "an open, interactive, online textbook for college music theory"
keywords: music theory, OER, university of idaho, inquiry-based
owner: Sean Butterfield
email: sbutterfield@uidaho.edu
published: 2017
github-repo: https://github.com/smbutterfield/ibmt17-18

# urls
url: https://smbutterfield.github.io
baseurl: /ibmt17-18

# collections
# each chapter of the book is a collection
# each chapter collection should be given a name value
collections:
  01-pitches-clefs-int:
    output: true
    name: 1) Pitches, Clefs, and Intervals
  02-scales-keys-triads-7chords:
    output: true
    name: 2) Scales, Keys, Triads, and Seventh Chords
  03-intro-rhythm:
    output: true
    name: 3) Rhythm and Regular Meters
  04-counterpoint-part1:
    output: true
    name: 4) Counterpoint 1
  05-counterpoint-part2:
    output: true
    name: 5) Counterpoint 2 and Embellishing Shapes
  06-intro-harmonic:
    output: true
    name: 6) Introduction to Harmonic Analysis
  07-harmonic-functions:
    output: true
    name: 7) Harmonic Function
  08-overtones:
    output: true
    name: 8) The Overtone Series
  09-partwriting-root-first:
    output: true
    name: 9) Voice-leading Using Root Position and First-inversion Triads
  10-partwriting-second-7chords:
    output: true
    name: 10) Voice-leading Using Seventh Chords and Second-inversion Chords
  11-ncts-embellishments:
    output: true
    name: 11) Non-chord tones and embellishments
  12-phrasing-texture:
    output: true
    name: 12) Phrasing and Texture
  13-sequences-voiceleading-exceptions:
    output: true
    name: 13) Sequences and Voice-leading Exceptions in Diatonic Harmony
  14-inst-ranges-trans-score-reduction:
    output: true
    name: 14) Instrument Ranges, Transposition, and Score Reduction

# ignore stuff
exclude: [oldOMTfiles, docs]
