# Inquiry-Based Music Theory
# OER Music text book, by Sean Butterfield and Evan Williamson
# project was inspired by and partially adapted from Open Music Theory https://github.com/openmusictheory/openmusictheory.github.io

# jekyll theme partly based on Lanyon, https://github.com/poole/lanyon
# OER Music text book, content adapted and created by smbutterfield
# jekyll theme adapted from Lanyon, https://github.com/poole/lanyon
# project set up by evanwill

# site info
title: Inquiry-Based Music Theory
tagline: OER Text Book
description: "an open, interactive, online textbook for college music theory"
keywords: music theory, OER, university of idaho, inquiry-based
owner: Sean Butterfield
email: sbutterfield@uidaho.edu
published: 2017
github-repo: https://github.com/smbutterfield/ibmt17-18

# urls
url: https://smbutterfield.github.io
baseurl: /ibmt17-18

# collections
# each unit of the book is a collection
# each unit collection should be given a name value
collections:
  01-pitches-clefs:
    output: true
    name: 1) Pitches and Clefs
  02-int-scales-keys:
    output: true
    name: 2) Intervals, Scales, and Keys
  03-triads-7chords-leadsheet:
    output: true
    name: 3) Triads, Seventh Chords, and Leadsheet Notation
  04-intro-rhythm:
    output: true
    name: 4) Rhythm and Regular Meters
  05-counterpoint-embell-shapes:
    output: true
    name: 5) Counterpoint and Embellishing Shapes
  06-intro-harmonic:
    output: true
    name: 6) Introduction to Harmonic Analysis
  07-harmonic-functions:
    output: true
    name: 7) Harmonic Function
  08-overtones:
    output: true
    name: 8) The Overtone Series
  09-non-chord-tones:
    output: true
    name: 9) Non-Chord Tones
  10-error-detection-intro-part-writing:
    output: true
    name: 10) Error Detection and an Introduction to Part-writing
  11-further-part-writing:
    output: true
    name: 11) Part-writing Using Seventh Chords and Second-inversion Chords 
  12-phrasing-texture:
    output: true
    name: 12) Phrasing and Texture
  13-sequences-voiceleading-exceptions:
    output: true
    name: 13) Sequences and Voice-leading Exceptions in Diatonic Harmony
  14-inst-ranges-trans-score-reduction:
    output: true
    name: 14) Instrument Ranges, Transposition, and Score Reduction

# ignore stuff
exclude: [oldOMTfiles, docs]
